### ISSUE TITLE
VPN Question

### ISSUE THREAD

**Issue by d-cas** [nice-table/bitmex-scaled-orders#12]
Apologies if this isn't the appropriate place for a question. I'm new to GitHub.

I'm running a VPN browser extension to mask my IP. But the web app is just a UI, correct? So even if I'm the extension is enabled, if the app is running on my PC, my true IP will be revealed, correct? Or is it masked if I access the app through the browser using the browser extension?

Also, will the app still work properly if I run the VPN globally instead of just through a browser extension?

Thank you!

**Comment by nice-table** [comment]
You are correct that the browser extension won't put the app in the VPN.

Running the VPN globally should work as you say.
