### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by rrcdr** [nice-table/bitmex-scaled-orders#14]
If I want to run this through a proxy how would I go about it? Do I need to do anything in addition to setting the proxy in Windows Internet properties?

**Comment by rrcdr** [comment]
When I set an incorrect proxy in Windows LAN settings, but also bypass local addresses I am able to connect to bitmex using this app. Is there any way I can force this app to connect to bitmex through a Windows proxy?

**Comment by nice-table** [comment]
If you setup your OS to use proxy, then this app should go through that proxy.
