### ISSUE TITLE
Looping Loading screen after entering API info

### ISSUE THREAD

**Issue by Lucky21110** [nice-table/bitmex-scaled-orders#15]
Hello,

I was able to install it but when I'm going to this page 

![image](https://user-images.githubusercontent.com/21016952/51366615-8340ac80-1ab4-11e9-890d-eb9b13758f26.png)

I set  API info and click save and I keep a Loading page all time same after refresh.
if I close and return in private he prompt me again for API but still loading ..

If I use Internet Explorer I have this 
![image](https://user-images.githubusercontent.com/21016952/51366718-f0544200-1ab4-11e9-9b44-9d7712bb7794.png)

Any Idea ?

**Comment by minhphuc429** [comment]
execute command `npm run proxy` before `npm run start`

**Comment by altcnews** [comment]
hi,
i've got the same looping screen after running 2 terminal fr proxy and start
anyone can help?
thank you

**Comment by nice-table** [comment]
Please try again with latest version. This version checks if the API key is valid.

Re-open if it still occurs.
