### ISSUE TITLE
TypeError: props.instruments.some is not a function 

### ISSUE THREAD

**Issue by ghost** [nice-table/bitmex-scaled-orders#19]
Yesterday it ran fine, today I get this on the browser after compiling sucessfully!...

![Capturar](https://user-images.githubusercontent.com/45380656/54527636-66204100-4972-11e9-83e3-e21ad0f6558a.PNG)

**Comment by nice-table** [comment]
Hi

Likely problems on Bitmexs end. Re-open of this continues
