### ISSUE TITLE
ETH/USD order book

### ISSUE THREAD

**Issue by itsgoofy** [nice-table/bitmex-scaled-orders#2]
Hi, love the project. Wanted to suggest adding in the new ETH perpetual swap contracts. Thanks!

**Comment by nice-table** [comment]
Hey

Glad to hear you like it :)

That's a good suggestion and a feature I want as well. I may start looking at this weekend, but it requires some refactoring so I'm not sure when it'll be ready.

**Comment by nice-table** [comment]
Re-opening issue. Will close when implemented.

**Comment by itsgoofy** [comment]
Awesome. Thanks boss.

**Comment by nice-table** [comment]
@itsgoofy ETHUSD and other instruments were added in the latest release :)
