### ISSUE TITLE
git pull

### ISSUE THREAD

**Issue by radeone** [nice-table/bitmex-scaled-orders#5]
did a git pull and the installation and i get compile errors will retest with fresh clone.

**Comment by bghveding** [comment]
Hey

Could you post the errors you get here?

**Comment by hashtagex** [comment]
Got same will post when home.

**Comment by nice-table** [comment]
Did you figure it out? I was able to do a clean clone and build without errors just now. Make sure you've ran `npm install` after pulling latest.

**Comment by nice-table** [comment]
Closing due to lack of response.
